---
- name: Install MongoDB in redhat
  when: ansible_os_family == "RedHat"
  block:

    - name: Install prerequisites
      ansible.builtin.yum:
        name: gnupg2
        update_cache: true

    - name: Clean yum repository
      ansible.builtin.file:
        state: absent
        path: /etc/yum.repos.d/mongodb.repo
      changed_when: false

    - name: Install MongoDB yum key
      ansible.builtin.yum_repository:
        name: mongodb
        description: MongoDB Repository
        baseurl: "{{ _mongodb_baseurl }}/{{ mongodb_release }}/{{ ansible_architecture }}/"
        enabled: true
        gpgcheck: true
        gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_release }}.asc"
      vars:
        _mongodb_baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org"

    - name: Update yum cache
      ansible.builtin.yum:
        update_cache: true

- name: Install MongoDB in debian
  when: ansible_os_family lower == "Debian"
  block:

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - gpg-agent
          - gnupg
        update_cache: true

    - name: Install MongoDB apt key
      ansible.builtin.apt_key:
        url: "https://pgp.mongodb.com/server-{{ mongodb_release }}.asc"

    - name: Clean apt repository
      ansible.builtin.file:
        state: absent
        path: /etc/apt/sources.list.d/mongodb.list
      changed_when: false

    - name: Add apt repository
      ansible.builtin.apt_repository:
        filename: mongodb
        repo: "{{ _repo }}"
      vars:
        _is_debian: "{{ (ansible_distribution | lower) == 'debian' }}"
        _distribution: "{{ ansible_distribution | lower }}"
        _os_release: "{{ ansible_distribution_release }}"
        _repo_mongodb: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt"
        _repo_ubuntu_url: "{{ _repo_mongodb }}/{{ _distribution }} {{ _os_release }}"
        _repo_ubuntu_name: "{{ 'main' if _is_debian else 'multiverse' }}"
        _repo: "{{ _repo_ubuntu_url }}/mongodb-org/{{ mongodb_release }} {{ _repo_ubuntu_name }}"

    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true
