---
- name: Install apt repository
  when: ansible_facts.os_family == "Debian"
  block:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - gnupg
          - apt-transport-https
          - python3-debian
        update_cache: true

    - name: Set apt repository facts
      ansible.builtin.set_fact:
        is_deb882: "{{ is_deb882_debian or is_deb882_ubuntu }}"
      vars:
        _distro: "{{ ansible_facts.distribution }}"
        _distro_ver: "{{ ansible_facts.distribution_version }}"
        is_deb882_debian: "{{ (_distro == 'Debian') and (_distro_ver is version('11', '>=')) }}"
        is_deb882_ubuntu: "{{ (_distro == 'Ubuntu') and (_distro_ver is version('22.04', '>=')) }}"

    - name: Set repo gpg key fact
      ansible.builtin.set_fact:
        mongodb_repo_gpg_key: "{{ url }}"
      vars:
        version: "{{ mongodb_repo_release | string }}"
        url: "https://pgp.mongodb.com/server-{{ version.split('.') | first }}.0.asc"

    - name: Clean apt repository
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/etc/apt/sources.list.d/mongodb.list"
        - "/etc/apt/sources.list.d/mongodb.sources"
      changed_when: false

    - name: Deploy legacy apt repository definition
      when: not is_deb882 | bool
      block:
        - name: Install MongoDB apt key
          ansible.builtin.apt_key:
            url: "{{ mongodb_repo_gpg_key }}"

        - name: Add Debian apt repository
          ansible.builtin.apt_repository:
            filename: mongodb
            repo: "{{ _repo }}"
          vars:
            _distro: "{{ ansible_facts.distribution }}"
            _distro_rel: "{{ ansible_facts.distribution }}"
            _repo_apt_base: "deb [ arch=amd64,arm64 ] {{ mongodb_repo_baseurl }}/apt/{{ _distro | lower }}"
            _repo_apt_component: "{{ 'main' if (_distro == 'Debian') else 'multiverse' }}"
            _repo: "{{ _repo_apt_base }} {{ _distro_rel }}/mongodb-org/{{ mongodb_repo_release }} {{ _repo_apt_component }}"
          changed_when: false

    - name: Install deb882 repository
      ansible.builtin.deb822_repository:
        name: mongodb
        uris: "{{ mongodb_repo_baseurl }}/apt/{{ _distro | lower }}"
        suites: "{{ ansible_facts.distribution_release }}/mongodb-org/{{ mongodb_repo_release }}"
        components: "{{ 'main' if (_distro == 'Debian') else 'multiverse' }}"
        signed_by: "{{ mongodb_repo_gpg_key }}"
        state: present
        enabled: true
      vars:
        _distro: "{{ ansible_facts.distribution }}"
      changed_when: false
      when: is_deb882 | bool

    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true

- name: Install yum repository
  when: ansible_facts.os_family == "RedHat"
  block:
    - name: Install prerequisites
      ansible.builtin.dnf:
        name: gnupg2
        update_cache: true

    - name: Clean yum repository
      ansible.builtin.file:
        state: absent
        path: /etc/yum.repos.d/mongodb.repo
      changed_when: false

    - name: Install MongoDB yum key
      ansible.builtin.yum_repository:
        name: mongodb
        description: MongoDB Repository
        baseurl: "{{ _mongodb_yum_base }}/{{ mongodb_repo_release }}/{{ ansible_facts.architecture }}/"
        enabled: true
        gpgcheck: true
        gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_repo_release }}.asc"
      vars:
        _mongodb_yum_base: "{{ mongodb_repo_baseurl }}/yum/redhat/$releasever/mongodb-org"
      changed_when: false

    - name: Update yum cache
      ansible.builtin.dnf:
        update_cache: true
