---
- name: Verify

  hosts: all

  vars:
    mongodb_packages:
      - mongodb-org
      - mongodb-org-mongos

  tasks:

    - name: Check mongodb-org package availability for Debian derivatives
      ansible.builtin.shell: set -o pipefail && apt-cache search {{ item }} | awk '{print $1}' | grep "^{{ item }}$"
      loop: "{{ mongodb_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Check mongodb-org package availability for RedHat derivatives
      ansible.builtin.shell: yum info {{ item }}
      loop: "{{ mongodb_packages }}"
      when: ansible_os_family == 'RedHat'
